/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
 //This file is generated by AWS amplify for specially for user authentication process, you can directly replace the whole file with your aws-exports.js
    const awsmobile = {
    "aws_project_region": "YOUR REGION",
    "aws_cognito_identity_pool_id":
        "YOUR Cognito IdentityPOOL ID",
    "aws_cognito_region": "YOUR COGNITO REGION",
    "aws_user_pools_id": "YOur user POOL ID",
    "aws_user_pools_web_client_id": "Your web client ID",
    "oauth": {}
};


export default awsmobile;